<?xml version="1.0" encoding="utf-8"?><Database Name="NoobBotDatabase" Class="NoobBotDatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=HAL2015;Initial Catalog=NoobBotDatabase;Integrated Security=True;Connect Timeout=60;Encrypt=False;TrustServerCertificate=True" SettingsObjectName="Installer.Properties.Settings" SettingsPropertyName="NoobBotDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.smilies" Member="smilies">
    <Type Name="smilies">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="unicode" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>